### ISSUE TITLE
Using left mouse button toggles fullscreen

### ISSUE THREAD

**Issue by lafoxxx92** [RPCS3/rpcs3-binaries-win#1]
I have some controller buttons mapped to mouse.
While not exactly a bug, using Left mouse button toggles fullscreen during gameplay.
Possible to change this behaviour so that the gameplay is not interrupted? You still can use Alt-Enter.

**Comment by zardoy** [comment]
This should have been issued in main repository. However there is a fix for you:

Config -> Emulator tab -> uncheck the box *Ignore double clicks for Fullscreen* in _viewport_ section
