### ISSUE TITLE
Anyone fix this issue yet. I can not continue from the hdd or from the save state. Please see below for the log:

### ISSUE THREAD

**Issue by WrothPython59** [RPCS3/rpcs3-binaries-win#4]
Anyone fix this issue yet. I can not continue from the hdd or from the save state. Please see below for the log: 

- SYS: RPCS3 v0.0.27-14876-44b3709d Alpha | master
- SYS: AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 63.91 GiB RAM | TSC: 3.693GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-04-15T18:11:59
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 6950 XT' running on driver 2.0.258
- SYS: Firmware version: 4.9
S UPDATER: RPCS3 is up to date!
S PPU: Enabled: Non-Java Mode Fixup
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 6950 XT' running on driver 2.0.258
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.
S Input: The pad mode was changed to Single-threaded
S Input: XInput device 0 connected
S GUI: Boot successful.
S PPU: LLVM: Loaded module v5-kusa-Ae2VYAd9UMbRRieaSHTrzH-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-AMtFTPXHnSJh7cz3ZJoEf1-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-NPNQFRq2kt1YM8HH573zXm-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Ua0T2AstFbfNgsrXunvTM4-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-PApYYtC3QQWN1FNQFX9pzb-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-WmjrJCSaGbRfeb1j6n81kv-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-f6tttpRMVbhYCPSqat9ANY-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-mfET1kKJa1mcC4697YENqm-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ezTEZToYXwVjURvYaTsfMv-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-J78jV6y8zQmNknMy7Ueebz-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-8hPj0CXwVEjpzwMjHzFb1S-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-mQfbQavimu1NzdJkXvVF5K-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-5UFyhCyb7UF9Kfewsjh4hH-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-XGkLxKNyNHWTRM2cY5szqe-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-XpQqMhZ0oZu2YoPW418UQY-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-6n6K7agrwKzb5RWdTwC0Q8-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Kofa50dwbuPfXih3qfuugd-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-8N1o44jtP6crns1Mdd3Twx-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-sMxdTgkQxhQJvLJUNMjo5X-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-qNmtuhthLELb5RYGn5AcLQ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-fLCjgY4iqhpLgYhqg1sa2P-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-rA7bfAnPwa193nHEfs0wjH-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-LY7JQqZrcUoot319YrJQrn-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-pkUvwwSP03xs32uR4N8sgi-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-58UveCwWtdCnb2F6rh2Sxg-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-qwrWs7MGAvKJv5yAmmJdy3-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-NN5J4uSdKVE7jv0L8j7cQb-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-MJ804Tpc7ih01eTTx2Uuy2-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-nny5VCEy1tFR1CMm8kCJuJ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ooR9Xz0EYJVqE46jsi1EcN-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-EN7toePUm9vCbgVauXQM6v-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ZMKWrNUuY7f843dizSgCcw-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-bz3Awbii4sqRcZ4xbqYz5Y-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-m2XQtT0C12u8RgjX16cZY0-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Qc3xFi3P60R8jfRTfMzAAJ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-rHL4fWAZ99Cr12k3GnYdmV-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-K8eMNMdRMcRWLguid68EPL-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-H7RQoRTpVQmsFqXpYS3RM4-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Ho1S0p3q1fnEndTT0jFXwT-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ay8AL0PfHeRmkjXiqPPKmp-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-JWeporcuqiiS54vn41rnn2-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-mUNueqLGC8FMnjgY7jV3Ud-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-3b22eE89Rjm01mT3k33Lx5-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-q2fo66nWEHcdmJdSm5AbT1-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-X8K5FWkEuiyRHGAoonLrM3-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Zku4cTkwHE31Cs6FGqnwPg-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-myhKWRSMHxM0oeYZL1gLCu-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-YMmT5PM4ahS2bgR1oVZMUs-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-H2LbvhEJXYiEhow7PRAnUp-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Ez47x38aJSvb8v7A6E4Qaw-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-4T5y0RtghR7SThGi3VvjiQ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-fZzyCqGTA5tkRAg9C26vgK-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-KRV3tGAZKCe0EmRSf2Vc4R-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-UV84GNuTPLWqmAecdE3vpM-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-0sAWaN23VEx0Q3HKziPNn4-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-J6NgZ76JY6W9Sq0r9boJgA-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-bHz0uQxAcvRqx9WQPwKKze-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-gnAMMZmvsWmg10SxLL8qkK-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-5V7svbk9UyvFzQYgQxUouG-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-0WtTY6bi4pcp15ZZWw44iW-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-E8C8GLkat6P7FUdCnTT6vT-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-A3LWETeYe5GGv4ds97ntZ1-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-qZSe7eyy8vVaQCzSio5Qho-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-RYmLdE41MCXgyjrvJ0J98A-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-AgVkzc83iEXNxFSrpKvQEt-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-0Rb4zJYfECjqGHCZHA0hu7-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-WUSj6JQ2XR7CsJiqMHs9HG-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-5Vo4XHpLvCQdLQgUS29dYE-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-GjshQbz0gtjofexxyP924k-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-L6j2zMFF4GMRxVGvst56dH-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-iayeHsbfyCz2m9e5RF6eRe-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-6JVrq4CmK7XJjttdd75Anx-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-japhhuf4M3CR8UXtxhEh5E-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-fy57G11EtFgFbuL5Qa5gTs-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-jLQJz5ZLgTeH3FhEfuTYk9-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-hY98Ur67HP0Zs0NdxMSozW-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Uonh4oZAAo20LeiJjg5N29-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-796vT6NTKuSt5rxracgG00-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-P9Vep9dR3ntcG1Cv0bVgrm-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-p9armNKoU3QKwZYoGcU21F-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-QTAxE5t91Ev1Fr2armjiNw-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-q7qn0uEgJoetuprn8Zxiko-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-EQZjvbVMtRF00Gnh5TCGmy-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-LT4zSEouyMeQeQw6qreQvV-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-iNKvsC6jkGnESbnV3VWA0w-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-jdzv8j6UcYyEXdW5fRsjSz-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-hhrPrccL3SGSP2T4ptSf0c-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-2yanLKUta8995CdTPXkTqt-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-JiGCumjwAuQ1X2iPk5jAq9-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-MpksqTUGNt7gM6WgU3baFq-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-pww7E06M9Zeh7uuwZhi9Uk-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ZGTs160K83i5RWNCWat8R2-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-NqH41erUFtdegwAtiGZQAK-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-NA4EnnfTbkT4b9YTnJJ7Z2-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-MgQeToTCNNYrtL9Aqioe9p-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-E7zS7pvW0EAsCt7JMZVkzk-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-0PPX91goZe1e4eV65TdQba-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-GXXjf1W7TyosLr1pUAyiZV-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-h0ZVJMmVqRmtLVKEiXR2mc-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-C26qdHKb2dJSqNaMzaRp0G-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-JHPfziGcn9afsYzCWfVyCC-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-TEiUAvfwQxzEyPR33Nom26-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-GhWvfSKZ64mphcCQyiu4xs-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-bWiS2xS8tiG0vAQUf8QGQ5-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ceiGYKdWyrQAXW5Uy0VUJU-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Y6pdmUrTwVMdU3SMevQV4X-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Mv5FuuZ4kp1FWTh1CYvqPh-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-KvRi6ue6tqn9MbGuoCE0Rj-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-VvFpAeCc33yt1PTbr67KLh-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-sgYnLYrkZ5mUFJiS1ATtCs-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-8SbrmyjdmChoTnFkQXSTMc-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-UJLEmp1tFM6XFror0M2toL-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-XT9A1vkHjYakC3WtNm0C95-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ZbZ08qxwWGyd8SQdxd5V6u-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-gp7hmgQ8J6XmE5x4ieAU7N-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-6mEbefL3YjppxCjWe7EvSS-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-VHhZkL7h8yNSmyxecJGhUb-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-TKKFP8AHcJE1me2X96F4Fv-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-JzeWEng62G75JsXVYp00mG-00001G-znver3.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: SPU Runtime: Built 2965 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0010ce0)
S PPU: LLVM: Loaded module v5-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S PPU: LLVM: Loaded module v5-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v5-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-5MR5UPWcNoRKHsUNJqHbKV-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0010df0)
S PPU: LLVM: Loaded module v5-kusa-fLV79QqHgPi90UziTsWrHo-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23002d00)
S PPU: LLVM: Loaded module v5-kusa-t1xTtC1PVoW6Jh636RxJVQ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-2wS6UCQGvL8KpqZwEg6HX7-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23005600)
S PPU: LLVM: Loaded module v5-kusa-UnNP3fZh95wiCGy3Q0csRy-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23005700)
S PPU: LLVM: Loaded module v5-kusa-GidnR56pzgun0Z5aqipN0L-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x23005900)
S PPU: LLVM: Loaded module v5-kusa-8G8Siw0thFwb1Pcpoo0ZbQ-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libvdec.sprx” (id=0x23005a00)
S PPU: LLVM: Loaded module v5-kusa-ttuWcrR8vkrZXRoK2sr771-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsmvd2.sprx” (id=0x23005b00)
S PPU: LLVM: Loaded module v5-kusa-HiPA6t49xGUA4vnZ3HFZ0a-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libavcdec.sprx” (id=0x23005c00)
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/render/global.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/render/global.viv.bh” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/render/global.viv.bh” [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/char/Southern_Corner.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/char/Office_TroyD.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/audio/AEMS/aemsSfx.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/gui/frontend.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/font_extents.txt” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/gui/fonts/05_Title.ttf ” [1] x2
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_fe.euk” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_fe.fre” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_fe.euk-meta.xml” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_fe.fre-meta.xml” [1]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: Stat: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [x119]
E SYS: Stat: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [x119]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: Stat: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [x75]
E SYS: Stat: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [x75]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: Stat: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [x99]
E SYS: Stat: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [x99]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/gui/story.viv.bh” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/font_extents.txt” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/gui/fonts/05_Title.ttf ” [2] x2
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_sm.euk” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_sm.fre” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_sm.euk-meta.xml” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ntsc/locale/xloc_sm.fre-meta.xml” [1]
F {PPU[0x100000b] Thread () [0x00426410]} VM: Access violation writing location 0x0 (unmapped memory)
E SYS: Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/common/render/global.viv” [x122]
E SYS: Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/common/render/global.viv.bh” [x121]
E SYS: Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/common/render/global.viv.bh” [x128]
E SYS: Stat: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [x6]
E SYS: Stat: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [x6]
E SIG: Thread [cellAudio Thread] is too sleepy. Waiting for it 21809.772µs already!
E SIG: Thread [cellAudio Thread] is too sleepy. Waiting for it 39802.652µs already!

Running the following:

AMD 5900x
AMD 6950 XT
64 GB RAM

_Originally posted by @WrothPython59 in https://github.com/RPCS3/rpcs3/issues/11682#issuecomment-1509989008_

**Comment by WrothPython59** [comment]
This is for Def Jam Icon. 

Kind Regards.

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
