### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Haldrie** [RPCS3/rpcs3-binaries-win#5]
It's been a while since I used this emulator so when I loaded it up a few days ago and updated it I was surprised when it popped up on my 3rd monitor. My setup uses three monitors with my main monitor in the middle and one to the left and right of it. When I move the emulator to my main (center) monitor after it opens on the right most one (monitor 3) all the UI elements, including drop down menus, keep opening on the right monitor instead of opening with the current placement of the emulator on my center screen. I have been able to work around this by simply disconnecting my right monitor but it is a bit annoying having to do that every time I want to use the emulator and I am hoping this bug can be fixed soon. It worked on older versions but I can not recall what the version was before I updated though it has been some months since it was last opened. If you need more details please let me know. I just updated to v0.0.29 and even downloaded and setup a fresh copy to find that even with a fresh install this bug is still present. I am also running a nVidia GTX 1070Ti in case that is relevant.

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
