### ISSUE TITLE
Which tag for the last Qt5 version?

### ISSUE THREAD

**Issue by Darthagnon** [RPCS3/rpcs3-binaries-win#6]
I just noticed RPCS3 updated to Qt6 around v0.0.29 - anyone know what the last version before the Qt6 implementation was? I need it for my legacy PCs (incompatible with Qt6)

**Comment by Darthagnon** [comment]
**It seems to be [v0.0.28-15409](https://github.com/RPCS3/rpcs3-binaries-win/releases/tag/build-fd6829f7576da07e3bb90de8821834d3ce44610c) that is the last version with Qt5 and Win7 support.**

**Comment by Darthagnon** [comment]
I can't help wondering what benefit Qt6 gives that it was worth locking out a subset of users?

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
